# Generated by Django 5.0.4 on 2025-04-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_mep_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="parliamentary_term",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="politicalgroup",
            name="shortform",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
